name: Deploy Python project to function app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: membership-card-status # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'   # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub action'
      uses: actions/checkout@v2

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd
    - name: write email/db config to json
      run: |
        mkdir .jsonfiles
        touch .jsonfiles/email.json
        echo "${{secrets.EMAIL_DATA}}" >> .jsonfiles/email.json
        touch .jsonfiles/email_dev.json
        echo "${{secrets.EMAIL_DEV_DATA}}" >> .jsonfiles/email_dev.json
        touch .jsonfiles/database.json
        echo "${{secrets.DB_DATA}}" >> .jsonfiles/database.json
        touch .jsonfiles/wechat.json
        echo "${{secrets.WECHAT_DATA}}" >> .jsonfiles/wechat.json
        touch .jsonfiles/base_urls.json
        echo "${{secrets.BASE_URLS}}" >> .jsonfiles/base_urls.json
    - name: 'Run Azure Functions action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}